// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: routeguide/v1/routeguide.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationRouteGuideGetFeature = "/routeguide.v1.RouteGuide/GetFeature"
const OperationRouteGuideListFeatures = "/routeguide.v1.RouteGuide/ListFeatures"
const OperationRouteGuideRecordRoute = "/routeguide.v1.RouteGuide/RecordRoute"
const OperationRouteGuideRouteChat = "/routeguide.v1.RouteGuide/RouteChat"

type RouteGuideHTTPServer interface {
	// GetFeature A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(context.Context, *Point) (*Feature, error)
	// ListFeatures A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(*Rectangle, RouteGuide_ListFeaturesServer) error
	// RecordRoute A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(RouteGuide_RecordRouteServer) error
	// RouteChat A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(RouteGuide_RouteChatServer) error
}

func RegisterRouteGuideHTTPServer(s *http.Server, srv RouteGuideHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/routeguide/features/{latitude}/{longitude}", _RouteGuide_GetFeature0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/routeguide/features", _RouteGuide_ListFeatures0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/routeguide/record-route", _RouteGuide_RecordRoute0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/routeguide/route-chat", _RouteGuide_RouteChat0_HTTP_Handler(srv))
}

type RouteGuide_ListFeaturesHTTPServer struct {
	http.ServerStream
}

func (x *RouteGuide_ListFeaturesHTTPServer) Send(m *Feature) error {
	return x.ServerStream.Send(m)
}

type RouteGuide_RecordRouteHTTPServer struct {
	http.ServerStream
}

func (x *RouteGuide_RecordRouteHTTPServer) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ServerStream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
func (x *RouteGuide_RecordRouteHTTPServer) SendAndClose(m *RouteSummary) error {
	return x.ServerStream.SendAndClose(m)
}

type RouteGuide_RouteChatHTTPServer struct {
	http.ServerStream
}

func (x *RouteGuide_RouteChatHTTPServer) Send(m *RouteNote) error {
	return x.ServerStream.Send(m)
}
func (x *RouteGuide_RouteChatHTTPServer) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ServerStream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RouteGuide_GetFeature0_HTTP_Handler(srv RouteGuideHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Point
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRouteGuideGetFeature)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFeature(ctx, req.(*Point))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Feature)
		return ctx.Result(200, reply)
	}
}

func _RouteGuide_ListFeatures0_HTTP_Handler(srv RouteGuideHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Rectangle
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		stream := http.NewServerSentEventServerStream(ctx)
		http.SetOperation(ctx, OperationRouteGuideListFeatures)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			stream.SetContext(ctx)
			return nil, srv.ListFeatures(req.(*Rectangle), &RouteGuide_ListFeaturesHTTPServer{ServerStream: stream})
		})
		_, err := h(ctx, &in)
		return stream.Close(err)
	}
}

func _RouteGuide_RecordRoute0_HTTP_Handler(srv RouteGuideHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		stream, err := http.NewWebSocketServerStream(ctx)
		if err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRouteGuideRecordRoute)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			stream.SetContext(ctx)
			return nil, srv.RecordRoute(&RouteGuide_RecordRouteHTTPServer{ServerStream: stream})
		})
		_, err = h(ctx, nil)
		return stream.Close(err)
	}
}

func _RouteGuide_RouteChat0_HTTP_Handler(srv RouteGuideHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		stream, err := http.NewWebSocketServerStream(ctx)
		if err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRouteGuideRouteChat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			stream.SetContext(ctx)
			return nil, srv.RouteChat(&RouteGuide_RouteChatHTTPServer{ServerStream: stream})
		})
		_, err = h(ctx, nil)
		return stream.Close(err)
	}
}

type RouteGuideHTTPClient interface {
	// GetFeature A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(ctx context.Context, req *Point, opts ...http.CallOption) (rsp *Feature, err error)
	// ListFeatures A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(ctx context.Context, req *Rectangle, opts ...http.CallOption) (RouteGuide_ListFeaturesClient, error)
	// RecordRoute A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(ctx context.Context, opts ...http.CallOption) (RouteGuide_RecordRouteClient, error)
	// RouteChat A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(ctx context.Context, opts ...http.CallOption) (RouteGuide_RouteChatClient, error)
}

type RouteGuideHTTPClientImpl struct {
	cc *http.Client
}

func NewRouteGuideHTTPClient(client *http.Client) RouteGuideHTTPClient {
	return &RouteGuideHTTPClientImpl{client}
}

type RouteGuide_ListFeaturesHTTPClient struct {
	http.ClientStream
}

func (x *RouteGuide_ListFeaturesHTTPClient) Recv() (*Feature, error) {
	m := new(Feature)
	if err := x.ClientStream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

type RouteGuide_RecordRouteHTTPClient struct {
	http.ClientStream
	ctx     context.Context
	cc      *http.Client
	pattern string
	opts    []http.CallOption
}

func (x *RouteGuide_RecordRouteHTTPClient) open(m *Point) error {
	if x.ClientStream != nil {
		return nil
	}
	opts := x.opts
	path := http.BuildPath(x.pattern, m)
	stream, err := x.cc.WebSocket(x.ctx, path, opts...)
	if err != nil {
		return err
	}
	x.ClientStream = stream
	return nil
}

func (x *RouteGuide_RecordRouteHTTPClient) CloseSend() error {
	if err := x.open(nil); err != nil {
		return err
	}
	return x.ClientStream.CloseSend()
}

func (x *RouteGuide_RecordRouteHTTPClient) Send(m *Point) error {
	if err := x.open(m); err != nil {
		return err
	}
	return x.ClientStream.Send(m)
}
func (x *RouteGuide_RecordRouteHTTPClient) CloseAndRecv() (*RouteSummary, error) {
	if err := x.open(nil); err != nil {
		return nil, err
	}
	m := new(RouteSummary)
	if err := x.ClientStream.CloseAndRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

type RouteGuide_RouteChatHTTPClient struct {
	http.ClientStream
	ctx     context.Context
	cc      *http.Client
	pattern string
	opts    []http.CallOption
}

func (x *RouteGuide_RouteChatHTTPClient) open(m *RouteNote) error {
	if x.ClientStream != nil {
		return nil
	}
	opts := x.opts
	path := http.BuildPath(x.pattern, m)
	stream, err := x.cc.WebSocket(x.ctx, path, opts...)
	if err != nil {
		return err
	}
	x.ClientStream = stream
	return nil
}

func (x *RouteGuide_RouteChatHTTPClient) CloseSend() error {
	if err := x.open(nil); err != nil {
		return err
	}
	return x.ClientStream.CloseSend()
}

func (x *RouteGuide_RouteChatHTTPClient) Send(m *RouteNote) error {
	if err := x.open(m); err != nil {
		return err
	}
	return x.ClientStream.Send(m)
}
func (x *RouteGuide_RouteChatHTTPClient) Recv() (*RouteNote, error) {
	if err := x.open(nil); err != nil {
		return nil, err
	}
	m := new(RouteNote)
	if err := x.ClientStream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GetFeature A simple RPC.
//
// Obtains the feature at a given position.
//
// A feature with an empty name is returned if there's no feature at the given
// position.
func (c *RouteGuideHTTPClientImpl) GetFeature(ctx context.Context, in *Point, opts ...http.CallOption) (*Feature, error) {
	var out Feature
	pattern := "/v1/routeguide/features/{latitude}/{longitude}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRouteGuideGetFeature),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListFeatures A server-to-client streaming RPC.
//
// Obtains the Features available within the given Rectangle.  Results are
// streamed rather than returned at once (e.g. in a response message with a
// repeated field), as the rectangle may cover a large area and contain a
// huge number of features.
func (c *RouteGuideHTTPClientImpl) ListFeatures(ctx context.Context, in *Rectangle, opts ...http.CallOption) (RouteGuide_ListFeaturesClient, error) {
	pattern := "/v1/routeguide/features"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("text/event-stream"),
		http.ContentType("application/protojson"),
		http.Operation(OperationRouteGuideListFeatures),
		http.PathTemplate(pattern),
	}, opts...)
	stream, err := c.cc.ServerSentEvent(ctx, "GET", path, nil, opts...)
	if err != nil {
		return nil, err
	}
	return &RouteGuide_ListFeaturesHTTPClient{ClientStream: stream}, nil
}

// RecordRoute A client-to-server streaming RPC.
//
// Accepts a stream of Points on a route being traversed, returning a
// RouteSummary when traversal is completed.
func (c *RouteGuideHTTPClientImpl) RecordRoute(ctx context.Context, opts ...http.CallOption) (RouteGuide_RecordRouteClient, error) {
	pattern := "/v1/routeguide/record-route"
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationRouteGuideRecordRoute),
		http.PathTemplate(pattern),
	}, opts...)
	return &RouteGuide_RecordRouteHTTPClient{ctx: ctx, cc: c.cc, pattern: pattern, opts: opts}, nil
}

// RouteChat A Bidirectional streaming RPC.
//
// Accepts a stream of RouteNotes sent while a route is being traversed,
// while receiving other RouteNotes (e.g. from other users).
func (c *RouteGuideHTTPClientImpl) RouteChat(ctx context.Context, opts ...http.CallOption) (RouteGuide_RouteChatClient, error) {
	pattern := "/v1/routeguide/route-chat"
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationRouteGuideRouteChat),
		http.PathTemplate(pattern),
	}, opts...)
	return &RouteGuide_RouteChatHTTPClient{ctx: ctx, cc: c.cc, pattern: pattern, opts: opts}, nil
}
