// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: routeguide/v1/routeguide.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Points are represented as latitude-longitude pairs in the E7 representation
// (degrees multiplied by 10**7 and rounded to the nearest integer).
// Latitudes should be in the range +/- 90 degrees and longitude should be in
// the range +/- 180 degrees (inclusive).
type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      int32                  `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     int32                  `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_routeguide_v1_routeguide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_routeguide_v1_routeguide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_routeguide_v1_routeguide_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// A latitude-longitude rectangle, represented as two diagonally opposite
// points "lo" and "hi".
type Rectangle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One corner of the rectangle.
	Lo *Point `protobuf:"bytes,1,opt,name=lo,proto3" json:"lo,omitempty"`
	// The other corner of the rectangle.
	Hi            *Point `protobuf:"bytes,2,opt,name=hi,proto3" json:"hi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rectangle) Reset() {
	*x = Rectangle{}
	mi := &file_routeguide_v1_routeguide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rectangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rectangle) ProtoMessage() {}

func (x *Rectangle) ProtoReflect() protoreflect.Message {
	mi := &file_routeguide_v1_routeguide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rectangle.ProtoReflect.Descriptor instead.
func (*Rectangle) Descriptor() ([]byte, []int) {
	return file_routeguide_v1_routeguide_proto_rawDescGZIP(), []int{1}
}

func (x *Rectangle) GetLo() *Point {
	if x != nil {
		return x.Lo
	}
	return nil
}

func (x *Rectangle) GetHi() *Point {
	if x != nil {
		return x.Hi
	}
	return nil
}

// A feature names something at a given point.
//
// If a feature could not be named, the name is empty.
type Feature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the feature.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The point where the feature is detected.
	Location      *Point `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_routeguide_v1_routeguide_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_routeguide_v1_routeguide_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_routeguide_v1_routeguide_proto_rawDescGZIP(), []int{2}
}

func (x *Feature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Feature) GetLocation() *Point {
	if x != nil {
		return x.Location
	}
	return nil
}

// A RouteNote is a message sent while at a given point.
type RouteNote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The location from which the message is sent.
	Location *Point `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// The message to be sent.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteNote) Reset() {
	*x = RouteNote{}
	mi := &file_routeguide_v1_routeguide_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteNote) ProtoMessage() {}

func (x *RouteNote) ProtoReflect() protoreflect.Message {
	mi := &file_routeguide_v1_routeguide_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteNote.ProtoReflect.Descriptor instead.
func (*RouteNote) Descriptor() ([]byte, []int) {
	return file_routeguide_v1_routeguide_proto_rawDescGZIP(), []int{3}
}

func (x *RouteNote) GetLocation() *Point {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *RouteNote) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// A RouteSummary is received in response to a RecordRoute rpc.
//
// It contains the number of individual points received, the number of
// detected features, and the total distance covered as the cumulative sum of
// the distance between each point.
type RouteSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of points received.
	PointCount int32 `protobuf:"varint,1,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
	// The number of known features passed while traversing the route.
	FeatureCount int32 `protobuf:"varint,2,opt,name=feature_count,json=featureCount,proto3" json:"feature_count,omitempty"`
	// The distance covered in metres.
	Distance int32 `protobuf:"varint,3,opt,name=distance,proto3" json:"distance,omitempty"`
	// The duration of the traversal in seconds.
	ElapsedTime   int32 `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteSummary) Reset() {
	*x = RouteSummary{}
	mi := &file_routeguide_v1_routeguide_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSummary) ProtoMessage() {}

func (x *RouteSummary) ProtoReflect() protoreflect.Message {
	mi := &file_routeguide_v1_routeguide_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSummary.ProtoReflect.Descriptor instead.
func (*RouteSummary) Descriptor() ([]byte, []int) {
	return file_routeguide_v1_routeguide_proto_rawDescGZIP(), []int{4}
}

func (x *RouteSummary) GetPointCount() int32 {
	if x != nil {
		return x.PointCount
	}
	return 0
}

func (x *RouteSummary) GetFeatureCount() int32 {
	if x != nil {
		return x.FeatureCount
	}
	return 0
}

func (x *RouteSummary) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *RouteSummary) GetElapsedTime() int32 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

var File_routeguide_v1_routeguide_proto protoreflect.FileDescriptor

const file_routeguide_v1_routeguide_proto_rawDesc = "" +
	"\n" +
	"\x1erouteguide/v1/routeguide.proto\x12\rrouteguide.v1\x1a\x1cgoogle/api/annotations.proto\"A\n" +
	"\x05Point\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x05R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x05R\tlongitude\"W\n" +
	"\tRectangle\x12$\n" +
	"\x02lo\x18\x01 \x01(\v2\x14.routeguide.v1.PointR\x02lo\x12$\n" +
	"\x02hi\x18\x02 \x01(\v2\x14.routeguide.v1.PointR\x02hi\"O\n" +
	"\aFeature\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\blocation\x18\x02 \x01(\v2\x14.routeguide.v1.PointR\blocation\"W\n" +
	"\tRouteNote\x120\n" +
	"\blocation\x18\x01 \x01(\v2\x14.routeguide.v1.PointR\blocation\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x93\x01\n" +
	"\fRouteSummary\x12\x1f\n" +
	"\vpoint_count\x18\x01 \x01(\x05R\n" +
	"pointCount\x12#\n" +
	"\rfeature_count\x18\x02 \x01(\x05R\ffeatureCount\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x05R\bdistance\x12!\n" +
	"\felapsed_time\x18\x04 \x01(\x05R\velapsedTime2\xbc\x03\n" +
	"\n" +
	"RouteGuide\x12r\n" +
	"\n" +
	"GetFeature\x12\x14.routeguide.v1.Point\x1a\x16.routeguide.v1.Feature\"6\x82\xd3\xe4\x93\x020\x12./v1/routeguide/features/{latitude}/{longitude}\x12c\n" +
	"\fListFeatures\x12\x18.routeguide.v1.Rectangle\x1a\x16.routeguide.v1.Feature\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/routeguide/features0\x01\x12j\n" +
	"\vRecordRoute\x12\x14.routeguide.v1.Point\x1a\x1b.routeguide.v1.RouteSummary\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/routeguide/record-route(\x01\x12i\n" +
	"\tRouteChat\x12\x18.routeguide.v1.RouteNote\x1a\x18.routeguide.v1.RouteNote\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/routeguide/route-chat(\x010\x01Bl\n" +
	"\x1eio.grpc.examples.routeguide.v1B\x0fRouteGuideProtoP\x01Z7github.com/go-kratos/kratos-layout/api/routeguide/v1;v1b\x06proto3"

var (
	file_routeguide_v1_routeguide_proto_rawDescOnce sync.Once
	file_routeguide_v1_routeguide_proto_rawDescData []byte
)

func file_routeguide_v1_routeguide_proto_rawDescGZIP() []byte {
	file_routeguide_v1_routeguide_proto_rawDescOnce.Do(func() {
		file_routeguide_v1_routeguide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeguide_v1_routeguide_proto_rawDesc), len(file_routeguide_v1_routeguide_proto_rawDesc)))
	})
	return file_routeguide_v1_routeguide_proto_rawDescData
}

var file_routeguide_v1_routeguide_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_routeguide_v1_routeguide_proto_goTypes = []any{
	(*Point)(nil),        // 0: routeguide.v1.Point
	(*Rectangle)(nil),    // 1: routeguide.v1.Rectangle
	(*Feature)(nil),      // 2: routeguide.v1.Feature
	(*RouteNote)(nil),    // 3: routeguide.v1.RouteNote
	(*RouteSummary)(nil), // 4: routeguide.v1.RouteSummary
}
var file_routeguide_v1_routeguide_proto_depIdxs = []int32{
	0, // 0: routeguide.v1.Rectangle.lo:type_name -> routeguide.v1.Point
	0, // 1: routeguide.v1.Rectangle.hi:type_name -> routeguide.v1.Point
	0, // 2: routeguide.v1.Feature.location:type_name -> routeguide.v1.Point
	0, // 3: routeguide.v1.RouteNote.location:type_name -> routeguide.v1.Point
	0, // 4: routeguide.v1.RouteGuide.GetFeature:input_type -> routeguide.v1.Point
	1, // 5: routeguide.v1.RouteGuide.ListFeatures:input_type -> routeguide.v1.Rectangle
	0, // 6: routeguide.v1.RouteGuide.RecordRoute:input_type -> routeguide.v1.Point
	3, // 7: routeguide.v1.RouteGuide.RouteChat:input_type -> routeguide.v1.RouteNote
	2, // 8: routeguide.v1.RouteGuide.GetFeature:output_type -> routeguide.v1.Feature
	2, // 9: routeguide.v1.RouteGuide.ListFeatures:output_type -> routeguide.v1.Feature
	4, // 10: routeguide.v1.RouteGuide.RecordRoute:output_type -> routeguide.v1.RouteSummary
	3, // 11: routeguide.v1.RouteGuide.RouteChat:output_type -> routeguide.v1.RouteNote
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_routeguide_v1_routeguide_proto_init() }
func file_routeguide_v1_routeguide_proto_init() {
	if File_routeguide_v1_routeguide_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeguide_v1_routeguide_proto_rawDesc), len(file_routeguide_v1_routeguide_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routeguide_v1_routeguide_proto_goTypes,
		DependencyIndexes: file_routeguide_v1_routeguide_proto_depIdxs,
		MessageInfos:      file_routeguide_v1_routeguide_proto_msgTypes,
	}.Build()
	File_routeguide_v1_routeguide_proto = out.File
	file_routeguide_v1_routeguide_proto_goTypes = nil
	file_routeguide_v1_routeguide_proto_depIdxs = nil
}
