// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: todo/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_TODO_UNSPECIFIED      ErrorReason = 0
	ErrorReason_TODO_NOT_FOUND        ErrorReason = 1
	ErrorReason_TODO_INVALID_ARGUMENT ErrorReason = 2
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "TODO_UNSPECIFIED",
		1: "TODO_NOT_FOUND",
		2: "TODO_INVALID_ARGUMENT",
	}
	ErrorReason_value = map[string]int32{
		"TODO_UNSPECIFIED":      0,
		"TODO_NOT_FOUND":        1,
		"TODO_INVALID_ARGUMENT": 2,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_todo_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_todo_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_todo_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_todo_v1_error_reason_proto protoreflect.FileDescriptor

const file_todo_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1atodo/v1/error_reason.proto\x12\atodo.v1*R\n" +
	"\vErrorReason\x12\x14\n" +
	"\x10TODO_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTODO_NOT_FOUND\x10\x01\x12\x19\n" +
	"\x15TODO_INVALID_ARGUMENT\x10\x02BJ\n" +
	"\atodo.v1P\x01Z1github.com/go-kratos/kratos-layout/api/todo/v1;v1\xa2\x02\tAPITodoV1b\x06proto3"

var (
	file_todo_v1_error_reason_proto_rawDescOnce sync.Once
	file_todo_v1_error_reason_proto_rawDescData []byte
)

func file_todo_v1_error_reason_proto_rawDescGZIP() []byte {
	file_todo_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_todo_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_v1_error_reason_proto_rawDesc), len(file_todo_v1_error_reason_proto_rawDesc)))
	})
	return file_todo_v1_error_reason_proto_rawDescData
}

var file_todo_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_todo_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: todo.v1.ErrorReason
}
var file_todo_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_todo_v1_error_reason_proto_init() }
func file_todo_v1_error_reason_proto_init() {
	if File_todo_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_v1_error_reason_proto_rawDesc), len(file_todo_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_todo_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_todo_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_todo_v1_error_reason_proto_enumTypes,
	}.Build()
	File_todo_v1_error_reason_proto = out.File
	file_todo_v1_error_reason_proto_goTypes = nil
	file_todo_v1_error_reason_proto_depIdxs = nil
}
