// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: todo/v1/todo.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Todo is the canonical representation of a todo item.
type Todo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned unique identifier. Read-only on create.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Short human-readable title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Detailed description or notes for the todo item.
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// Whether the todo item has been completed.
	Completed bool `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	// Time at which the todo item was created. Server-assigned, read-only.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Time at which the todo item was last modified. Server-assigned, read-only.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_todo_v1_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Todo) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Todo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Todo) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// TodoSet is a paginated collection of todo items returned by ListTodos.
type TodoSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The page of todo items in the order requested by ListTodosRequest.order_by.
	Todos []*Todo `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	// Token used to retrieve the next page via ListTodosRequest.page_token.
	// Empty when there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoSet) Reset() {
	*x = TodoSet{}
	mi := &file_todo_v1_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoSet) ProtoMessage() {}

func (x *TodoSet) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoSet.ProtoReflect.Descriptor instead.
func (*TodoSet) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{1}
}

func (x *TodoSet) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

func (x *TodoSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// CreateTodoRequest is the input for TodoService.CreateTodo.
type CreateTodoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The todo item to create. The id, create_time, and update_time fields are
	// ignored on input and populated by the server in the response.
	Todo          *Todo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTodoRequest) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

// GetTodoRequest is the input for TodoService.GetTodo.
type GetTodoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the todo item to retrieve.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoRequest) Reset() {
	*x = GetTodoRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoRequest) ProtoMessage() {}

func (x *GetTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoRequest.ProtoReflect.Descriptor instead.
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{3}
}

func (x *GetTodoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ListTodosRequest is the input for TodoService.ListTodos.
type ListTodosRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Maximum number of todo items to return in a single page.
	// The server may apply a default and a maximum when unset or out of range.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Token from a previous response's next_page_token used to fetch
	// the next page. Leave empty to request the first page.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. The standard list filter.
	// Supported fields:
	//   - `title` (i.e. `title:"bug"`)
	//   - `content` (i.e. `content:"docs"`)
	//   - `completed` (i.e. `completed` or `NOT completed`)
	//   - `create_time` range (i.e. `create_time>="2026-01-01T00:00:00Z"`)
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. A comma-separated list of fields to order by.
	// Supported fields:
	//   - `id`
	//   - `title`
	//   - `create_time`
	//   - `update_time`
	//
	// Append ` desc` to a field for descending order, e.g. `create_time desc`.
	// Defaults to ascending order when no direction is supplied.
	OrderBy       string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosRequest) Reset() {
	*x = ListTodosRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest) ProtoMessage() {}

func (x *ListTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosRequest.ProtoReflect.Descriptor instead.
func (*ListTodosRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{4}
}

func (x *ListTodosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTodosRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListTodosRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListTodosRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// UpdateTodoRequest is the input for TodoService.UpdateTodo.
type UpdateTodoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The todo carrying the new field values. todo.id identifies the target
	// record and must be set.
	Todo *Todo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	// Set of field paths in todo to overwrite. Fields not listed are left
	// unchanged. Use a single path of `*` to replace every mutable field.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoRequest) Reset() {
	*x = UpdateTodoRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest) ProtoMessage() {}

func (x *UpdateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTodoRequest) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

func (x *UpdateTodoRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteTodoRequest is the input for TodoService.DeleteTodo.
type DeleteTodoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the todo item to delete.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTodoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// WatchTodosRequest is the input for TodoService.WatchTodos.
// It selects which todo items the resulting event stream observes.
type WatchTodosRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Maximum number of todo items returned in the initial snapshot
	// before live events begin streaming.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Page token used to resume from a prior snapshot.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. List filter expression. Same syntax as ListTodosRequest.filter.
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. Order specification. Same syntax as ListTodosRequest.order_by.
	OrderBy       string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTodosRequest) Reset() {
	*x = WatchTodosRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTodosRequest) ProtoMessage() {}

func (x *WatchTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTodosRequest.ProtoReflect.Descriptor instead.
func (*WatchTodosRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{7}
}

func (x *WatchTodosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *WatchTodosRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *WatchTodosRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *WatchTodosRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// SyncTodoRequest is a single client message in the SyncTodos bidirectional
// stream. The action field selects which operation to perform on the server.
type SyncTodoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The operation to perform. One of `create`, `update`, or `delete`.
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// Payload for `create` and `update` actions. Ignored for `delete`.
	Todo *Todo `protobuf:"bytes,2,opt,name=todo,proto3" json:"todo,omitempty"`
	// Identifier of the target todo. Required for `delete` and `update`.
	Id int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	// Field mask used by `update` actions to limit which fields are overwritten.
	// Ignored for `create` and `delete`.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncTodoRequest) Reset() {
	*x = SyncTodoRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTodoRequest) ProtoMessage() {}

func (x *SyncTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTodoRequest.ProtoReflect.Descriptor instead.
func (*SyncTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{8}
}

func (x *SyncTodoRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SyncTodoRequest) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

func (x *SyncTodoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SyncTodoRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// TodoEvent is a server-sent message describing a change to a todo item.
// It is emitted by both WatchTodos and SyncTodos streams.
type TodoEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The change that occurred. One of `created`, `updated`, or `deleted`.
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// The todo item after the change. For `deleted` events only the id field
	// is guaranteed to be populated.
	Todo *Todo `protobuf:"bytes,2,opt,name=todo,proto3" json:"todo,omitempty"`
	// Time at which the change was observed by the server.
	EventTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoEvent) Reset() {
	*x = TodoEvent{}
	mi := &file_todo_v1_todo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoEvent) ProtoMessage() {}

func (x *TodoEvent) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoEvent.ProtoReflect.Descriptor instead.
func (*TodoEvent) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{9}
}

func (x *TodoEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TodoEvent) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

func (x *TodoEvent) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

var File_todo_v1_todo_proto protoreflect.FileDescriptor

const file_todo_v1_todo_proto_rawDesc = "" +
	"\n" +
	"\x12todo/v1/todo.proto\x12\atodo.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x01\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\bR\tcompleted\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"V\n" +
	"\aTodoSet\x12#\n" +
	"\x05todos\x18\x01 \x03(\v2\r.todo.v1.TodoR\x05todos\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\";\n" +
	"\x11CreateTodoRequest\x12&\n" +
	"\x04todo\x18\x01 \x01(\v2\r.todo.v1.TodoB\x03\xe0A\x02R\x04todo\"%\n" +
	"\x0eGetTodoRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x81\x01\n" +
	"\x10ListTodosRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"}\n" +
	"\x11UpdateTodoRequest\x12&\n" +
	"\x04todo\x18\x01 \x01(\v2\r.todo.v1.TodoB\x03\xe0A\x02R\x04todo\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"(\n" +
	"\x11DeleteTodoRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x82\x01\n" +
	"\x11WatchTodosRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"\x99\x01\n" +
	"\x0fSyncTodoRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12!\n" +
	"\x04todo\x18\x02 \x01(\v2\r.todo.v1.TodoR\x04todo\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x81\x01\n" +
	"\tTodoEvent\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12!\n" +
	"\x04todo\x18\x02 \x01(\v2\r.todo.v1.TodoR\x04todo\x129\n" +
	"\n" +
	"event_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime2\xe9\x04\n" +
	"\vTodoService\x12W\n" +
	"\n" +
	"CreateTodo\x12\x1a.todo.v1.CreateTodoRequest\x1a\r.todo.v1.Todo\"\x1e\x82\xd3\xe4\x93\x02\x18:\x04todo\"\x10/v1/todos/create\x12I\n" +
	"\aGetTodo\x12\x17.todo.v1.GetTodoRequest\x1a\r.todo.v1.Todo\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/todos/{id}\x12P\n" +
	"\tListTodos\x12\x19.todo.v1.ListTodosRequest\x1a\x10.todo.v1.TodoSet\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/todos/list\x12W\n" +
	"\n" +
	"UpdateTodo\x12\x1a.todo.v1.UpdateTodoRequest\x1a\r.todo.v1.Todo\"\x1e\x82\xd3\xe4\x93\x02\x18:\x04todo\x1a\x10/v1/todos/update\x12X\n" +
	"\n" +
	"DeleteTodo\x12\x1a.todo.v1.DeleteTodoRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/todos/{id}\x12W\n" +
	"\n" +
	"WatchTodos\x12\x1a.todo.v1.WatchTodosRequest\x1a\x12.todo.v1.TodoEvent\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/todos/watch0\x01\x12X\n" +
	"\tSyncTodos\x12\x18.todo.v1.SyncTodoRequest\x1a\x12.todo.v1.TodoEvent\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/todos/sync(\x010\x01BZ\n" +
	"\x18io.grpc.examples.todo.v1B\tTodoProtoP\x01Z1github.com/go-kratos/kratos-layout/api/todo/v1;v1b\x06proto3"

var (
	file_todo_v1_todo_proto_rawDescOnce sync.Once
	file_todo_v1_todo_proto_rawDescData []byte
)

func file_todo_v1_todo_proto_rawDescGZIP() []byte {
	file_todo_v1_todo_proto_rawDescOnce.Do(func() {
		file_todo_v1_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_v1_todo_proto_rawDesc), len(file_todo_v1_todo_proto_rawDesc)))
	})
	return file_todo_v1_todo_proto_rawDescData
}

var file_todo_v1_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_todo_v1_todo_proto_goTypes = []any{
	(*Todo)(nil),                  // 0: todo.v1.Todo
	(*TodoSet)(nil),               // 1: todo.v1.TodoSet
	(*CreateTodoRequest)(nil),     // 2: todo.v1.CreateTodoRequest
	(*GetTodoRequest)(nil),        // 3: todo.v1.GetTodoRequest
	(*ListTodosRequest)(nil),      // 4: todo.v1.ListTodosRequest
	(*UpdateTodoRequest)(nil),     // 5: todo.v1.UpdateTodoRequest
	(*DeleteTodoRequest)(nil),     // 6: todo.v1.DeleteTodoRequest
	(*WatchTodosRequest)(nil),     // 7: todo.v1.WatchTodosRequest
	(*SyncTodoRequest)(nil),       // 8: todo.v1.SyncTodoRequest
	(*TodoEvent)(nil),             // 9: todo.v1.TodoEvent
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 11: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_todo_v1_todo_proto_depIdxs = []int32{
	10, // 0: todo.v1.Todo.create_time:type_name -> google.protobuf.Timestamp
	10, // 1: todo.v1.Todo.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: todo.v1.TodoSet.todos:type_name -> todo.v1.Todo
	0,  // 3: todo.v1.CreateTodoRequest.todo:type_name -> todo.v1.Todo
	0,  // 4: todo.v1.UpdateTodoRequest.todo:type_name -> todo.v1.Todo
	11, // 5: todo.v1.UpdateTodoRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 6: todo.v1.SyncTodoRequest.todo:type_name -> todo.v1.Todo
	11, // 7: todo.v1.SyncTodoRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 8: todo.v1.TodoEvent.todo:type_name -> todo.v1.Todo
	10, // 9: todo.v1.TodoEvent.event_time:type_name -> google.protobuf.Timestamp
	2,  // 10: todo.v1.TodoService.CreateTodo:input_type -> todo.v1.CreateTodoRequest
	3,  // 11: todo.v1.TodoService.GetTodo:input_type -> todo.v1.GetTodoRequest
	4,  // 12: todo.v1.TodoService.ListTodos:input_type -> todo.v1.ListTodosRequest
	5,  // 13: todo.v1.TodoService.UpdateTodo:input_type -> todo.v1.UpdateTodoRequest
	6,  // 14: todo.v1.TodoService.DeleteTodo:input_type -> todo.v1.DeleteTodoRequest
	7,  // 15: todo.v1.TodoService.WatchTodos:input_type -> todo.v1.WatchTodosRequest
	8,  // 16: todo.v1.TodoService.SyncTodos:input_type -> todo.v1.SyncTodoRequest
	0,  // 17: todo.v1.TodoService.CreateTodo:output_type -> todo.v1.Todo
	0,  // 18: todo.v1.TodoService.GetTodo:output_type -> todo.v1.Todo
	1,  // 19: todo.v1.TodoService.ListTodos:output_type -> todo.v1.TodoSet
	0,  // 20: todo.v1.TodoService.UpdateTodo:output_type -> todo.v1.Todo
	12, // 21: todo.v1.TodoService.DeleteTodo:output_type -> google.protobuf.Empty
	9,  // 22: todo.v1.TodoService.WatchTodos:output_type -> todo.v1.TodoEvent
	9,  // 23: todo.v1.TodoService.SyncTodos:output_type -> todo.v1.TodoEvent
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_todo_v1_todo_proto_init() }
func file_todo_v1_todo_proto_init() {
	if File_todo_v1_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_v1_todo_proto_rawDesc), len(file_todo_v1_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todo_v1_todo_proto_goTypes,
		DependencyIndexes: file_todo_v1_todo_proto_depIdxs,
		MessageInfos:      file_todo_v1_todo_proto_msgTypes,
	}.Build()
	File_todo_v1_todo_proto = out.File
	file_todo_v1_todo_proto_goTypes = nil
	file_todo_v1_todo_proto_depIdxs = nil
}
